// <auto-generated />
using System;
using Education.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Education.Persistence.Migrations
{
    [DbContext(typeof(EducationDbContext))]
    partial class EducationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Edutacion.Domain.Curso", b =>
                {
                    b.Property<Guid>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Precio")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CursoId");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            CursoId = new Guid("9be73948-eb42-4c1b-b622-76db57a8b803"),
                            Descripcion = "Curso de c# basico",
                            FechaCreacion = new DateTime(2022, 1, 22, 20, 54, 13, 639, DateTimeKind.Local).AddTicks(8168),
                            FechaPublicacion = new DateTime(2024, 1, 22, 20, 54, 13, 640, DateTimeKind.Local).AddTicks(7068),
                            Precio = 56m,
                            Titulo = "C# desde cero hasta avanzado"
                        },
                        new
                        {
                            CursoId = new Guid("5941e611-b68d-49c8-8643-b25ee342750a"),
                            Descripcion = "Curso de java",
                            FechaCreacion = new DateTime(2022, 1, 22, 20, 54, 13, 640, DateTimeKind.Local).AddTicks(7576),
                            FechaPublicacion = new DateTime(2024, 1, 22, 20, 54, 13, 640, DateTimeKind.Local).AddTicks(7581),
                            Precio = 25m,
                            Titulo = "Master en Java spring desde las raices"
                        },
                        new
                        {
                            CursoId = new Guid("9bd5c5d1-80e8-4561-b3ea-6c0abdb742a4"),
                            Descripcion = "Curso de unit test para net core",
                            FechaCreacion = new DateTime(2022, 1, 22, 20, 54, 13, 640, DateTimeKind.Local).AddTicks(7590),
                            FechaPublicacion = new DateTime(2024, 1, 22, 20, 54, 13, 640, DateTimeKind.Local).AddTicks(7591),
                            Precio = 1000m,
                            Titulo = "Master en UNIT Test con CQRS"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
