// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Azucena.Vasquez.Infrastructure.Data.Audit.Entities
{
    public partial class AuditLog
    {
        public int AuditLogId { get; set; }
        public DateTime Time { get; set; }
        public string UserName { get; set; }
        public string Service { get; set; }
        public string Action { get; set; }
        public long Duration { get; set; }
        public string Ipaddress { get; set; }
        public string Browser { get; set; }
        public string Request { get; set; }
        public string Response { get; set; }
        public string Error { get; set; }
    }
}